@startuml
title 定时发布问卷

participant "供应商中心" as vc
participant "用户中心" as uc
participant "消息中心" as mc
actor "供应商用户" as cpm


activate vc
vc -> vc: 查询将要生效的问卷列表
note left of vc: 发布时间小于当前时间\n 问卷状态：待发布


vc -> vc: 查询问卷状态：只有待发布和暂停的\n才能进行发布操作
vc -> vc: 修改状态
note left of vc: 如果是第一次发布 发送站内信
vc -> vc: 校验是否第一次发布 发送站内信
vc -> uc: 分批查询供应商id集合

activate uc
uc -> uc: 查询关联的所有用户集合
uc --> vc: 返回结果集
deactivate uc
vc -> vc: 设置消息体
vc -> vc: 提取用户id与供应商并匹配
vc -> vc: 拼装发布对象 [供应商id、供应商名称、用户id]
vc -> mc:  推送站内信到目标供应商
deactivate vc


activate mc #DarkSalmon
mc -> mc: 创建定时任务

mc -> mc: 5分钟后触发定时任务
mc -> cpm: 开始推送站内信
deactivate mc

activate cpm
cpm -> cpm: 收到问卷提醒



@enduml