@startuml
'https://plantuml.com/sequence-diagram
title 产品查询接口
autonumber

participant "shoppingX/订单中心" as shop
participant "产品中心" as p
participant "产品规则库" as gzk

shop -> p: 产品查询
activate p
note left of shop: '产品编码 \n sku编码'

p -> p:查询产品基本信息
alt 销售品
p -> p: 查询规则关联的销售品信息
p -> p: 根据销售品上配置的item及展示比例计算实际展示item
p -> p: 查询涉及的具体sku
end
p -> p: 获取实际sku对应的价格信息
p -> p: 查询可销售渠道
p -> p: 根据spu查询类目信息

p -> p: 组装出参

return
@enduml