server:
  port: 8083
  #context-path: /rua
girl:
  cupsize: A
  age: 18
  height: 170

###################  MyBatis 配置  ###################
mybatis:
    type-aliases-package: com.example.demo.Gentity
    mapper-locations: classpath:/myBatis/*Mapper.xml

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/bsp?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 159753Wang
    tomcat:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      min-evictable-idle-time-millis: 300000
      time-between-eviction-runs-millis: 60000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: true
      test-on-return: true