@startuml
title svc迁移使用dts增量
autonumber
participant "应用" as app
database "oracle" as oracle
database "老DB(自建mysql)" as old
database "新DB(RDS)" as new
old -> new : 手动执行结构同步
old -> new : 手动备份、同步某一时间点的全量数据
new -> new : 稽核全量数据
oracle -> new : 使用DTS核对时间位点，进行增量同步
note left of new:等待数据迁移任务的进度变更为增量迁移\n并显示为无延迟状态或延迟时间低于5秒
new -> new : 稽核数据(数量及业务稽核)
app -> new :连接RDS
app -> app :业务回归
@enduml