@startuml
title 库存接口幂等设计

autonumber
participant "订单中心" as trade
participant "产品中心" as prod
participant "redis" as redis
participant "数据库" as db

trade -> prod :库存核心接口调用
note left of trade: 锁定库存 \n扣减库存 \n还原库存
alt 跳过幂等校验
    prod -> trade : 通过
else 不跳过幂等校验
    prod -> prod :生成uniqueId
    prod -> redis : get(uniqueId)
    alt  存在幂等缓存
        prod -> trade : 幂等校验失败 \n throw 重复请求库存接口\n该订单号关联商品数据没有改变
    else redis幂等缓存为空
        prod -> redis : set(uniqueId)
        note left of redis: 失效时间暂定一天
        prod -> db : 根据uniqueId查询库存事件
        prod -> prod : 过滤失效的库存事件,订单修改等
        alt 查询结果包含此uniqueId
            prod -> trade :  幂等校验失败 \n重复提交，库存事件已存在
        else 查询结果无此uniqueId
            prod -> trade : 幂等校验成功
        end
        prod -> prod :处理业务逻辑
        prod -> db : 放置库存事件记录
        alt 程序非幂等报错
            prod -> redis :  delete(uniqueId)
    end

    end


end

@enduml